services:

  auth_service:

    build:
      context: ./auth_service
      dockerfile: Dockerfile

    container_name: auth_service

    ports:
      - "8001:8000"

    env_file:
      - ./auth_service/.env

    depends_on:
      - auth_db


  auth_db:

    image: postgres:16

    container_name: auth_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db

    ports:
      - "5433:5432"

    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
  
  catalog_service:

    build:
      context: ./catalog_service
      dockerfile: Dockerfile

    container_name: catalog_service

    ports:
      - "8002:8000"

    env_file:
      - ./catalog_service/.env

    depends_on:
      - catalog_db


  catalog_db:

    image: postgres:16

    container_name: catalog_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog_db

    ports:
      - "5434:5432"

    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data


  watchlist_service:

    build:
      context: ./watchlist_service
      dockerfile: Dockerfile

    container_name: watchlist_service

    restart: always

    ports:
      - "8003:8000"

    env_file:
      - ./watchlist_service/.env

    depends_on:
      - watchlist_db
      - catalog_service


  watchlist_db:

    image: postgres:16

    container_name: watchlist_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watchlist_db

    ports:
      - "5435:5432"

    volumes:
      - watchlist_postgres_data:/var/lib/postgresql/data



volumes:

  auth_postgres_data:

  catalog_postgres_data:

  watchlist_postgres_data:


